export const GET_FILMS = {
    INIT: "GET_FILMS_INIT",
    SUCCESS: "GET_FILMS_SUCCESS",
    ERROR: "GET_FILMS_ERROR"
}

export const GET_FILM_INFO = {
    INIT: "GET_FILM_INFO_INIT",
    SUCCESS: "GET_FILM_INFO_SUCCESS",
    ERROR: "GET_FILM_INFO_ERROR"
}